
platform :ios, '9.0'
use_frameworks!

target 'Project Three' do
	
	pod 'SwiftGifOrigin', :git => 'https://github.com/bahlo/SwiftGif', :tag => ‘v1.6’

	pod ‘SideMenu’
    
       pod 'Parse'
	
	pod ‘SwiftSpinner’
    

    
end
